version: "3"
services:
  tavernai:
    build: .
    container_name: tavernai
    hostname: tavernai
    image: tavernai/tavernai:latest
    ports:
      - "8000"
    volumes:
      - "/home/node/app/public"
      - "/home/node/app"
    restart: unless-stopped
